In [2]:
import logging
import six
import sys
import gensim
import warnings
from collections import Counter
import gensim as gensim
from gensim.models import Word2Vec
from gensim.models.keyedvectors import KeyedVectors
from gensim.models.word2vec import LineSentence
import jieba

import re

%matplotlib inline

In [3]:
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'


In [4]:
###直接调用训练好的词向量  人民日报
from gensim.models.keyedvectors import KeyedVectors
word_vectors = KeyedVectors.load_word2vec_format('F:/data/tdata/sgns.renmin.txt', binary=False) 

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-c8d36b88fc4c>", line 3, in <module>
    word_vectors = KeyedVectors.load_word2vec_format('F:/data/tdata/sgns.renmin.txt', binary=False)
  File "d:\ProgramData\Anaconda3\lib\site-packages\gensim\models\keyedvectors.py", line 1547, in load_word2vec_format
    return _load_word2vec_format(
  File "d:\ProgramData\Anaconda3\lib\site-packages\gensim\models\utils_any2vec.py", line 275, in _load_word2vec_format
    with utils.open(fname, 'rb') as fin:
  File "d:\ProgramData\Anaconda3\lib\site-packages\smart_open\smart_open_lib.py", line 177, in open
    fobj = _shortcut_open(
  File "d:\ProgramData\Anaconda3\lib\site-packages\smart_open\smart_open_lib.py", line 363, in _shortcut_open
    return _builtin_open(local_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundE

TypeError: object of type 'NoneType' has no len()

In [6]:
from gensim.models import KeyedVectors
word_vectors  = KeyedVectors.load_word2vec_format('E:/word/sgns.literature.word.bz2', binary=False)


In [5]:
from gensim.models import KeyedVectors
word_vectors  = KeyedVectors.load_word2vec_format('D:\wenben\8月12下午 文本分析\sgns.literature.word\sgns.literature.word', binary=False)


FileNotFoundError: [Errno 2] No such file or directory: 'D:\\wenben\\8月12下午 文本分析\\sgns.literature.word\\sgns.literature.word'

可以试试D:\wenben\8月12下午 文本分析\sgns.literature.word\sgns.literature.word

可以回去下载一下试一下，想问一下

In [ ]:
wv2 = zh_model.most_similar(u"兰州", topn=20)  # 20个最相关的
print(u"和【兰州】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【兰州】最相关的20个词：

乌鲁木齐 0.6235544681549072
西安 0.600725531578064
铜川 0.5990307331085205
新乡 0.5939702987670898
西宁 0.5931434631347656
呼和浩特 0.5908531546592712
哈尔滨 0.5853298306465149
石家庄 0.5825376510620117
襄垣 0.5777226686477661
茶淀 0.5767880082130432
大西北 0.5717238783836365
南宁 0.5713056921958923
银川 0.571183979511261
高台县 0.5709978938102722
甘肃 0.5703372955322266
张掖 0.5692179799079895
玉门镇 0.56831955909729
平山县 0.5679912567138672
霍州 0.567303478717804
佳木斯 0.5655432939529419
-----



In [ ]:
wv2 = word_vectors.most_similar(u"甘肃", topn=20)  # 20个最相关的
print(u"和【甘肃】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【甘肃】最相关的20个词：

甘肃省 0.7631230354309082
陕西 0.7361190319061279
宁夏 0.7196593284606934
青海 0.7131429314613342
陇南 0.6725785732269287
定西地区 0.6309807300567627
兰州 0.6159172654151917
贵州 0.6143765449523926
固原 0.6102784872055054
内蒙古 0.6095123887062073
临洮 0.6041218638420105
定西 0.6027911305427551
平凉 0.5996686220169067
武威地区 0.5957146286964417
四川 0.595056414604187
天水市 0.5941694974899292
武威 0.5922673940658569
天祝藏族自治县 0.5920180082321167
临夏 0.5912328958511353
靖远 0.5890480875968933
-----



In [ ]:
wv2 = word_vectors.most_similar(u"百度", topn=20)  # 20个最相关的
print(u"和【百度】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【百度】最相关的20个词：

腾讯 0.6199362874031067
BAT 0.5927181243896484
贴吧 0.5788369178771973
奇虎 0.577629029750824
搜狗 0.5576536655426025
百度公司 0.5566093921661377
搜狐 0.5477172136306763
网易 0.5457697510719299
优酷网 0.542261004447937
糯米网 0.540283203125
搜索引擎 0.5363065004348755
土豆网 0.5316785573959351
应用程序 0.530573844909668
人人网 0.5304474830627441
LBS 0.5290228724479675
风温由 0.5289266109466553
App 0.5285270810127258
苹果应用商店 0.528480589389801
搜索框 0.518974244594574
优酷 0.518169641494751
-----



In [ ]:
wv2 = word_vectors.most_similar(u"华中科技大学", topn=20)  # 20个最相关的
print(u"和【华中科技大学】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【华中科技大学】最相关的20个词：

西安电子科技大学 0.6746385097503662
武汉理工大学 0.6736884713172913
东南大学 0.6620356440544128
南京工业大学 0.6579621434211731
中南大学 0.6552565097808838
华中科大 0.6531168222427368
湖南师范大学 0.6524401903152466
西南科技大学 0.6509807109832764
材料学院 0.6508315205574036
生命学院 0.6503276824951172
华南理工大学 0.6482797861099243
北京科技大学 0.6446981430053711
华北电力大学 0.6420555114746094
电子科技大学 0.6377374529838562
北京理工大学 0.6324993371963501
南京财经大学 0.6272202730178833
建筑学系 0.6258431673049927
陈婧 0.6250656247138977
南京邮电大学 0.6226168274879456
旅游系 0.6202101707458496
-----



In [ ]:
wv2 = word_vectors.most_similar(u"兰州大学", topn=20)  # 20个最相关的
print(u"和【兰州大学】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【兰州大学】最相关的20个词：

内蒙古农业大学 0.64217209815979
湖北大学 0.6369290351867676
宁夏大学 0.6315649747848511
经济学系 0.6295349597930908
西南大学 0.6285501718521118
数学力学系 0.6178983449935913
陕西师范大学 0.6165448427200317
福州大学 0.6163474321365356
四川师范大学 0.6161370873451233
武汉工业大学 0.613633930683136
石河子大学 0.6122087240219116
研究生部 0.6121171116828918
贵州大学 0.6113371253013611
湖南师范大学 0.6110628843307495
任继周 0.6101771593093872
西北师范大学 0.6101294159889221
数学科学学院 0.6101162433624268
华北电力大学 0.6087483167648315
西北民族大学 0.6085972785949707
顾秉林 0.6083161234855652
-----



In [ ]:
wv2 = word_vectors.most_similar(u"社科院", topn=20)  # 20个最相关的
print(u"和【社科院】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【社科院】最相关的20个词：

中国社科院 0.7163364887237549
中国社会科学院 0.6738505959510803
社会科学院 0.6710268259048462
社会学所 0.6678988337516785
孙元明 0.6413918733596802
梁启东 0.6352035999298096
社会学研究所 0.6274921894073486
农村发展所 0.6258655786514282
刘道兴 0.6253546476364136
世经所 0.6230249404907227
工经所 0.6206804513931274
北京市社会科学院 0.6171122789382935
农发所 0.6156880855560303
财贸所 0.6155264377593994
马列所 0.6148092150688171
法学所 0.6141024827957153
江苏省社科院 0.6133836507797241
台研所 0.6093935370445251
中国边疆史地研究中心 0.6063185930252075
四川省社科院 0.6019394397735596
-----



In [ ]:
wv2 = word_vectors.most_similar(u"社会学", topn=20)  # 20个最相关的
print(u"和【社会学】最相关的20个词：\n")
for word in wv2:
    print(word[0], word[1])
print("-----\n")

和【社会学】最相关的20个词：

历史学 0.703485369682312
经济学 0.6944149136543274
宗教学 0.6922945976257324
法学 0.6868265271186829
比较文学 0.6868042349815369
社会心理学 0.6863694787025452
民俗学 0.6836918592453003
发展经济学 0.6827443242073059
伦理学 0.6814084053039551
政治学 0.6794657707214355
文艺学 0.6736794114112854
人类学 0.6717830896377563
经济学说 0.670441210269928
人口学 0.6616834402084351
图书馆学 0.6602093577384949
民族学 0.6576277017593384
行政管理学 0.6574132442474365
法律学 0.6548317670822144
史学 0.6535594463348389
财政学 0.6531257629394531
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"社科院", u"社会学")
except KeyError:
    y1 = 0
print(u"【社科院】和【社会学】的相似度为：", y1)
print("-----\n")

【社科院】和【社会学】的相似度为： 0.4704938
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"北京大学", u"社会学")
except KeyError:
    y1 = 0
print(u"【北京大学】和【社会学】的相似度为：", y1)
print("-----\n")

【北京大学】和【社会学】的相似度为： 0.44370875
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"中山大学", u"社会学")
except KeyError:
    y1 = 0
print(u"【中山大学】和【社会学】的相似度为：", y1)
print("-----\n")

【中山大学】和【社会学】的相似度为： 0.38379064
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"南京大学", u"社会学")
except KeyError:
    y1 = 0
print(u"【南京大学】和【社会学】的相似度为：", y1)
print("-----\n")

【南京大学】和【社会学】的相似度为： 0.41460907
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"华中科技大学", u"社会学")
except KeyError:
    y1 = 0
print(u"【华中科技大学】和【社会学】的相似度为：", y1)
print("-----\n")

【华中科技大学】和【社会学】的相似度为： 0.3336188
-----



In [ ]:
print(word_vectors)
# 计算两个词的相似度/相关程度
try:
    y1 = word_vectors.similarity(u"百度", u"社会学")
except KeyError:
    y1 = 0
print(u"【百度】和【社会学】的相似度为：", y1)
print("-----\n")

【百度】和【社会学】的相似度为： 0.093279205
-----



In [ ]:
# 寻找不合群的词
y4 =word_vectors.doesnt_match(u"社会学 经济学 哲学 物理学".split())
print(u"不合群的词：", y4)
print("-----\n")

不合群的词： 物理学
-----



D:\annacoda\lib\site-packages\gensim\models\keyedvectors.py:877: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vectors = vstack(self.word_vec(word, use_norm=True) for word in used_words).astype(REAL)


In [ ]:
##安装
##pip install baidu-aip

  Created wheel for baidu-aip: filename=baidu_aip-2.2.18.0-py3-none-any.whl size=15225 sha256=5724d0e83f4a40cea85e0d42f4ef7cd131ecfc1a3221b8b2c67343250a339c4c
  Stored in directory: c:\users\liuhe\appdata\local\pip\cache\wheels\2a\6b\27\4509d0c71d5c33a5ec497bd9a8ecbee01023713fa6107066d7
Successfully built baidu-aip
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'D:\annacoda\python.exe -m pip install --upgrade pip' command.


In [ ]:
##调用相关包
from aip import AipNlp

In [ ]:
##常量APP_ID在百度云控制台中创建，常量API_KEY与SECRET_KEY是在创建完毕应用后，系统分配给用户的，均为字符串，用于标识用户，为访问做签名验证，可在AI服务控制台中的应用列表中查看。
##获取说明见链接：https://ai.baidu.com/ai-doc/REFERENCE/Ck3dwjgn3
APP_ID = '***'
API_KEY = '***'
SECRET_KEY = '***'
client = AipNlp(APP_ID, API_KEY, SECRET_KEY)

In [ ]:
##词向量表示接口提供中文词向量的查询功能。
word="社会"
client.wordEmbedding(word)

In [ ]:
##词义相似度：输入两个词，得到两个词的相似度结果。
result3 = client.wordSimEmbedding("社会","国家")

print(result3)

In [ ]:
##短文本相似度接口用来判断两个文本的相似度得分。
result1 = client.simnet("这件衣服颜色怎么样？","这件衣服价格怎么样")

print(result1)

{'log_id': 160233320034533944, 'texts': {'text_2': '这件衣服价格怎么样', 'text_1': '这件衣服颜色怎么样？'}, 'score': 0.876619}


文章分类
对文章按照内容类型进行自动分类，首批支持娱乐、体育、科技等26个主流内容类型，为文章聚类、文本内容分析等应用提供基础技术支持。

In [ ]:
title = "欧洲冠军杯足球赛"

content = "欧洲冠军联赛是欧洲足球协会联盟主办的年度足球比赛，代表欧洲俱乐部足球最高荣誉和水平，被认为是全世界最高素质、最具影响力以及最高水平的俱乐部赛事，亦是世界上奖金最高的足球赛事和体育赛事之一。"

""" 调用文章分类 """
client.topic(title, content)

{'log_id': 8977109743450100312,
 'item': {'lv2_tag_list': [{'score': 0.915631, 'tag': '足球'},
   {'score': 0.803507, 'tag': '国际足球'},
   {'score': 0.77813, 'tag': '英超'}],
  'lv1_tag_list': [{'score': 0.830915, 'tag': '体育'}]}}

参数名称	类型	详细说明
item	object	分类结果，包含一级与二级分类
+lv1_tag_list	array of objects	一级分类结果
+lv2_tag_list	array of objects	二级分类结果
++score	float	类别标签对应得分，范围0-1
++tag	string	类别标签

In [ ]:
##评论观点抽取接口用来提取一条评论句子的关注点和评论观点，并输出评论观点标签及评论观点极性。
text = "华为手机拍照很给力"

""" 调用评论观点抽取 """
client.commentTag(text);

""" 如果有可选参数 """
options = {}
options["type"] = 13

""" 带参数调用评论观点抽取 """
client.commentTag(text, options)

{'log_id': 5151802381157227129,
 'items': [{'sentiment': 2,
   'abstract': '华为手机<span>拍照很给力</span>',
   'prop': '拍照',
   'begin_pos': 8,
   'end_pos': 18,
   'adj': '给力'}]}

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from gensim.models.keyedvectors import KeyedVectors

In [ ]:
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

In [ ]:
# 选择词语
words_to_visualize = ['足球', '篮球', '游泳', '跑步']

# 获取词向量
word_vectors_to_visualize = [word_vectors[word] for word in words_to_visualize]

word_vectors_array = np.array(word_vectors_to_visualize) 

In [5]:
from whatlies import EmbeddingSet
from whatlies.language import SpacyLanguage

d:\ProgramData\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


AttributeError: module 'numpy' has no attribute 'typeDict'

In [ ]:
from whatlies import EmbeddingSet
from whatlies.language import SpacyLanguage

lang = SpacyLanguage("en_core_web_md")

words = ["cat", "dog", "fish", "kitten", "man", "woman",
         "king", "queen", "doctor", "nurse"]

emb = EmbeddingSet(*[lang[w] for w in words])
emb.plot_interactive(x_axis=emb["man"], y_axis=emb["woman"])

In [ ]:

# 使用 t-SNE 进行降维
tsne = TSNE(n_components=2, random_state=42)
embedded_vectors = tsne.fit_transform(word_vectors_to_visualize)

# 绘制可视化
plt.figure(figsize=(10, 6))
plt.scatter(embedded_vectors[:, 0], embedded_vectors[:, 1])
for i, word in enumerate(words_to_visualize):
    plt.annotate(word, (embedded_vectors[i, 0], embedded_vectors[i, 1]))
plt.title('Word Embedding Visualization')
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
plt.show()


In [ ]:
# 使用 t-SNE 进行降维，降低 perplexity 的值
tsne = TSNE(n_components=2, perplexity=1, random_state=42)


In [ ]:
embedded_vectors = tsne.fit_transform(word_vectors_array)

AttributeError: 'NoneType' object has no attribute 'split'

In [ ]:
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'


In [ ]:
print(word_vectors_array)
type(word_vectors_array)
word_vectors_array.shape

[[-0.027347  0.070783 -0.343744 ...  0.655656 -0.054512  0.040245]
 [-0.228249 -0.467796 -0.230872 ...  0.43272   0.340129  0.27908 ]
 [-0.0852   -0.034392 -0.212352 ...  0.129779 -0.118814  0.494388]
 ...
 [ 0.150019  0.139685 -0.046349 ... -0.322366  0.39754  -0.061939]
 [-0.116376  0.259957 -0.396093 ...  0.290762  0.093402  0.131013]
 [-0.24838  -0.155707  0.13223  ... -0.132338  0.059203 -0.082784]]


(10, 300)